[package]
name = "pms"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "^3.2.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
