[package]
name = "tsv2xlsx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xlsxwriter = "^0.3"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
