[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.release]
command = "cargo"
toolchain = "nightly"
args = ["build", "--release"]
dependencies = ["clippy"]
